# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
ENV["RAILS_ENV"] ||= "test"

require "byebug"
require "factory_bot"
require "munificent"
FactoryBot.find_definitions
World(FactoryBot::Syntax::Methods)

ENV["OTP_ISSUER"] = "Munificent admin (test)"
ENV["RAILS_ROOT"] = File.expand_path("../../test/dummy", __dir__)

require File.expand_path("../../test/dummy/config/environment", __dir__)

require "cucumber/rails"
require "webdrivers"
require "webdrivers/chromedriver"

require "webmock/cucumber"
driver_urls = Webdrivers::Common.subclasses.map(&:base_url)
WebMock.disable_net_connect!(allow_localhost: true, allow: driver_urls)

require "rspec/mocks"
require "cucumber/rspec/doubles"

require "authlogic/test_case"
Before do
  activate_authlogic
end

TEST_PORT = 30_001

Capybara.configure do |config|
  config.server = :puma, { Silent: true }
  config.server_port = TEST_PORT
end
ActionMailer::Base.default_url_options[:port] = TEST_PORT
ENV["APP_HOST"] = "127.0.0.1:#{TEST_PORT}"

ActionController::Base.allow_rescue = false

begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Before do
  if page.driver.browser.respond_to?(:manage)
    page.driver.browser.manage.window.maximize
  end
end

Before do
  create(:fundraiser, :active, name: "Default fundraiser")
end

After do
  ::RSpec::Mocks.verify
ensure
  ::RSpec::Mocks.teardown
end
