version: 2.1

orbs:
  ruby: circleci/ruby@1.4
  browser-tools: circleci/browser-tools@1.2

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.2-browsers # this is our primary docker image, where step commands run.
      - image: cimg/redis:6.2
      - image: cimg/postgres:13.5
        environment: # add POSTGRES environment variables.
          POSTGRES_USER: circleci
          POSTGRES_DB: munificent_admin_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    # environment variables specific to Ruby/Rails, applied to the primary container.
    environment:
      APP_HOST: 127.0.0.1:3000
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      CI: true
      FROM_EMAIL_ADDRESS: "munificent-admin@example.com"
      HMAC_SECRET: "c360bcae-df63-4616-808a-860f03d7da6b"
      PGHOST: 127.0.0.1
      PGPASSWORD: ""
      PGUSER: circleci
    steps:
      - browser-tools/install-chrome:
          replace-existing: true
      - browser-tools/install-chromedriver
      - run:
          name: Check install
          command: |
            google-chrome --version
            chromedriver --version
      - checkout
      - ruby/install-deps
      # Here we make sure that the secondary container boots
      # up before we run operations on the database.
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Database setup
          command: RAILS_ENV=test bundle exec rails db:schema:load --trace
      - run:
          name: Tests
          command: RAILS_ENV=test bundle exec rake
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  version: 2
  build_and_test: # The name of our workflow is "build_and_test"
    jobs: # The list of jobs we run as part of this workflow.
      - test # Then run test,
